### ISSUE TITLE
maintenance: upgrade ruby version to 2.1

### ISSUE THREAD

**Issue by herestomwiththeweather** [oscurrency/oscurrency#607]
Gemfile currently sets ruby version to 1.9.3.  Ruby version should be updated in Gemfile and gems that use ruby features that have been deprecated in 2.1 should be updated.

**Comment by buzzaz** [comment]
Hi Tom,

Great finding this message (after I sent out the last one.) I recall we
also deprecated our test server to Ruby 1.9.3, & wondered if it would come
back to bother us later. (It's in the doc notes.)

Is this something you would do, or would you like Carl's help? We are both
committed to seeing this through. Please direct, or leery us know. I'll add
this info to the same doc, in a "Remediations" section.

Thx.

AZ Zaidi
www.AbbasZaidi.com
415.966.9800 on PST.
"An organism coordinates a point of view." ~Terrence McKenna

**Comment by herestomwiththeweather** [comment]
cool. my testing for these changes will include testing the heroku installation script.  when the new commits are available, you should be able to update your test server (which will then be using ruby 2.1) with 'rake heroku:update' (see https://github.com/oscurrency/oscurrency/blob/master/lib/tasks/heroku.rake#L99)
