### ISSUE TITLE
Let user deactivate / cancel their own account

### ISSUE THREAD

**Issue by cgorringe** [oscurrency/oscurrency#611]
There doesn't appear to be a link or button for users to deactivate / cancel / delete their account from the system.  Could place this in the user's profile page?

**Comment by herestomwiththeweather** [comment]
that sounds right.  it would simply set deactivated for that person to true and log them out.

**Comment by herestomwiththeweather** [comment]
...and maybe an email notification of the self-deactivation to the support email.
