### ISSUE TITLE
New Members aren't auto-enrolled in default group

### ISSUE THREAD

**Issue by cgorringe** [oscurrency/oscurrency#613]
When a new member signs up for the timebank, they are not automatically enrolled or joined to the default group. At least not on the BACE timebank.  The new user has to explicitly click on the "Join group" link on the default group's home page.  

The user doesn't know that they have to do this, and finds they aren't authorized to post offers or requests, and they aren't listed or searchable in the people tab.

**Comment by buzzaz** [comment]
Can we fix this by auto-enrolling them in the BACE Timebank group?

AZ
Abbas Z. Zaidi ~ US Mobile: 1.415.966.9800 (PST zone)
Creative informationDesign Consultants www.eForte.net
<http://www.eforte.net/>
===========================================
Personal: AbbasZaidi.com <http://abbaszaidi.com/>/ Professional:
eForte.net/blog <http://eforte.net/blog>
Angel <https://angel.co/az-zaidi> | Linkedin
<http://www.linkedin.com/in/buzzaz> *|* Facebook
<http://facebook.com/buzzaz> | Twitter <http://twitter.com/buzzaz> | Quora
<http://www.quora.com/Abbas-Zaidi> *| *Timebank
<http://timebank.sfbace.org/people/2041-az-xedi>
===========================================
"An organism coordinates a point of view." ~ T McKenna
===========================================

**Comment by herestomwiththeweather** [comment]
d'oh! that is normally done by the install script.  however, in this case, that step was not performed due to being an upgrade from a version prior to the introduction of auto-enrolling.  the fix is easy though:

heroku run console
> p = Preference.first
> g = p.default_group
> g.update_attributes!(mandatory: true)

here is the commit that introduced the idea of a mandatory group: https://github.com/oscurrency/oscurrency/commit/a1efe31d8b1b160eb6d169240bf885d292532384

**Comment by buzzaz** [comment]
Wow, you don't lose any time.. I walk in after lunch with you, and issues
are already being closed.. At this rate, we could start thinking of that OS
currency bucket we were talking about ;~}
AZ.

AZ Zaidi
www.AbbasZaidi.com
415.966.9800 on PST.
"An organism coordinates a point of view." ~Terrence McKenna
