### ISSUE TITLE
Add 'Give Credit' button to profile page

### ISSUE THREAD

**Issue by cgorringe** [oscurrency/oscurrency#618]
We'd like to replace the small 'Credit' link with a larger "Give Credit" green button right above the box, so that it's more visible to the users.

**Comment by herestomwiththeweather** [comment]
i concur that this needs to be a button.  buttons (like new offer, new req, etc.) are currently blue (which i think is just the consequence of default for bootstrap) so, for now, i'll conservatively follow that default until someone with better css skills than me can improve.
